language: python
python:
  - "3.6"
install:
  - cd ChemCheck
  - pip install Pipfile
  - python -VV
  - pip freeze
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
